name: Assistant Release tests workflow in Bundled OpenSearch Dashboards
on:
  pull_request:
    branches: ['**']
env:
  CYPRESS_ASSISTANT_AGENT_INITIALIZE_REQUIRED: true
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.filter.outputs.tests }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            tests:
              - 'cypress/**/dashboards-assistant/**'

  tests:
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: dashboards assistant
      test-command: yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/dashboards-assistant/*'
      osd-serve-args: --assistant.chat.enabled=true --assistant.chat.rootAgentName="Cypress test agent"
