name: (ciGrouped)Bundle Snapshot based E2E Cypress tests workflow for core Dashboards
on:
  pull_request:
    branches: ['**']
    paths:
      - '**/*'
      - 'cypress/**/core-opensearch-dashboards/**'
      - 'cypress/utils/dashboards/**'
  push:
    branches: ['**']
    paths:
      - 'cypress/**/core-opensearch-dashboards/**'
      - 'cypress/utils/dashboards/**'

env:
  CI_GROUPS: "1,2,3,4,5,6,7,8,9"

jobs:
  set_spec:
    runs-on: 'ubuntu-latest'
    outputs:
      spec_ciGroups: ${{ steps.get_spec.outputs.spec_ciGroups }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Checkout cypress-test
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
          path: spec-detect
      - id: get_spec
        name: Get specs array
        run: |
          cd spec-detect
          result="["
          ## split CI_Groups into array
          IFS="," read -a groups <<< "${{ env.CI_GROUPS }}"
          for group in "${groups[@]}"; do
            IFS="," read -a SPEC_ARRAY <<< "$(npm run -s osd:ciGroup${group})"
            FORMATTED_SPEC="\""
            for i in "${SPEC_ARRAY[@]}"; do
              FORMATTED_SPEC+="cypress/integration/core-opensearch-dashboards/opensearch-dashboards/${i},"
            done
            FORMATTED_SPEC+="\""
            if [[ "${result}" != "[" ]];
            then
                result+=","
            fi
            result+="${FORMATTED_SPEC}"
          done

          result+=']';

          echo ${result}
          echo "spec_ciGroups=${result}" >> "$GITHUB_OUTPUT"

  tests-with-security:
    needs: ["set_spec"]
    strategy:
      fail-fast: false
      matrix:
        group: ${{ fromJSON(needs.set_spec.outputs.spec_ciGroups) }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Core Dashboards using Bundle Snapshot
      test-command: env CYPRESS_NO_COMMAND_LOG=1 CYPRESS_ML_COMMONS_DASHBOARDS_ENABLED=true CYPRESS_VISBUILDER_ENABLED=true CYPRESS_DATASOURCE_MANAGEMENT_ENABLED=true yarn cypress:run-with-security --browser chromium --spec '${{ matrix.group }}'
      osd-serve-args: --data_source.enabled=true --data_source.ssl.verificationMode=none --vis_builder.enabled=true --ml_commons_dashboards.enabled=true

  tests-without-security:
    needs: ["set_spec"]
    strategy:
      fail-fast: false
      matrix:
        group: ${{ fromJSON(needs.set_spec.outputs.spec_ciGroups) }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Core Dashboards using Bundle Snapshot
      test-command: env CYPRESS_NO_COMMAND_LOG=1 CYPRESS_ML_COMMONS_DASHBOARDS_ENABLED=true CYPRESS_VISBUILDER_ENABLED=true CYPRESS_DATASOURCE_MANAGEMENT_ENABLED=true yarn cypress:run-without-security --browser chromium --spec '${{ matrix.group }}'
      osd-serve-args: --data_source.enabled=true --data_source.ssl.verificationMode=none --vis_builder.enabled=true --ml_commons_dashboards.enabled=true
      security-enabled: false